const surpriseMe = [
  "a giraffe wearing sunglasses at a beach party",
  "a surreal painting of a fishbowl with floating islands",
  "a robot chef baking cupcakes in a futuristic kitchen",
  "a raccoon piloting a spaceship through a candy galaxy",
  "a watercolor illustration of a cozy library with flying books",
  "a snail racing in a tiny sports car on a racetrack",
  "a vintage postcard featuring a cat dressed as an explorer",
  "a dreamy landscape of giant mushrooms under a neon sky",
  "an octopus painting a masterpiece in an underwater studio",
  "a plush unicorn lounging on a cloud with rainbow pillows",
  "a time-traveling detective solving mysteries in Victorian London",
  "a 3D render of a cat cafe in a treehouse",
  "a fantasy city made entirely of candy and sweets",
  "a steampunk elephant with gears and goggles walking through a park",
  "a digital art piece of a dragon reading a book in a library",
  "a cozy cabin in the woods during a magical snowfall",
  "a colorful mural of dancing animals in a vibrant city",
  "a whimsical tea party hosted by woodland creatures",
  "a futuristic city skyline at sunset with flying cars",
  "a surreal portrait of a woman with flowers for hair",
  "a tiny hedgehog gardening in a miniature vegetable patch",
  "a retro diner in space with aliens as customers",
  "a robot painter creating landscapes on a distant planet",
  "a magical garden with glowing flowers and tiny fairies",
  "a futuristic train traveling through a neon-lit city",
  "a playful puppy wearing a superhero cape and mask",
  "a haunted house made of candy corn and chocolate",
  "a fantasy castle floating in the clouds surrounded by rainbows",
  "a dragon and a unicorn sharing a picnic in a meadow",
  "a retro spaceship landing in a suburban neighborhood",
  "a bear playing chess with a raccoon in a park",
  "a cosmic rollercoaster weaving through the stars",
  "a whimsical clock tower with animals as the timekeepers",
  "a surreal landscape where the sky is made of swirling colors",
  "a photo of a penguin sliding down a snowy hill in a tuxedo",
  "a cozy café in Paris run by cats and dogs",
  "a futuristic beach with holographic umbrellas and floating lounges",
  "a magical bookstore with enchanted books flying off the shelves",
  "a giant cupcake castle surrounded by candy mountains",
  "a lion in a suit giving a speech at a corporate meeting",
  "a dreamlike scene of a waterfall flowing into the sky",
  "a cartoon-style dinosaur enjoying a picnic in a city park",
  "a fantasy marketplace with mythical creatures selling goods",
  "a colorful train made of candy traveling through a whimsical landscape",
  "a robot librarian shelving books in a futuristic library",
  "a surreal sculpture garden with floating geometric shapes",
  "a garden of oversized flowers where fairies dance",
  "a painting of a whimsical treehouse village in the clouds",
  "a cozy living room with a talking fireplace and animated paintings",
  "a mermaid exploring an underwater treasure chest filled with gadgets",
];
export default surpriseMe;
